name: "Publish Release"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  repository-projects: write
  pull-requests: write

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM package

        run: |
          cd packages/core-wasm
          wasm-pack build --target web --out-dir ../../apps/desktop/src/pkg

      - name: Install dependencies
        run: pnpm install

      - name: Build and Publish
        uses: tauri-apps/tauri-action@v0
        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "DiscordWASM v__VERSION__"
          releaseBody: "Mise à jour automatique incluant le JSON."
          releaseDraft: false
          prerelease: false
          projectPath: ./apps/desktop

          includeUpdaterJson: true